LandProject.Web/Controllers/Home2Controller.cs
using LandProject.Web.Areas.Admin.Infrastructure.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LandProject.Service;
using LandProject.Common;
using LandProject.Web.Models;
using AutoMapper;
using LandProject.Model.Models;

namespace LandProject.Web.Controllers
{
    public class Home2Controller : Controller
    {
        IMenuGroupService _menugroupService;
        IMenuService _menuService;
        IAddressCommonService _addressCommonService;
        ILandNewsService _landNewsService;
		ICommonService _commonService;

        public Home2Controller(IMenuGroupService menugroupService,
        IMenuService menuService,
        IAddressCommonService addressCommonService,
		ICommonService commonService,
		ILandNewsService landNewsService)
        {
            _menugroupService = menugroupService;
            _menuService = menuService;
            _addressCommonService = addressCommonService;
            _landNewsService = landNewsService;
			_commonService = commonService;

		}
        // GET: Home2
        public ActionResult Index()
        {
            var homeViewModel = new HomeViewModel();
            var categoryWard = _addressCommonService.GetTotalLandNewsOfWards(571).ToList().OrderByDescending(x=>x.TotalLandNews);

			var slide = _commonService.GetSlide().ToList();
			ViewBag.Slide = slide;


			int pageSizeHot = int.Parse(ConfigHelper.GetByKey("PageSizeHot"));
			int pageSizeSale = int.Parse(ConfigHelper.GetByKey("PageSizeSale"));
			int pageSizeRent = int.Parse(ConfigHelper.GetByKey("PageSizeRent"));
			int keyLandHot = int.Parse(ConfigHelper.GetByKey("LandScheduleID"));

            //tin noi bat
            string filterHot = "ln.LandNewsScheduleID = "+ keyLandHot + "" + " and ln.IsDelete = 0 and ln.IsPublished = 1";
            var lstLandNewsHot = _landNewsService.GetAllByFilter(filterHot, "PublishedDate desc", 1, pageSizeHot).ToList();
            var lstLandNewsHotVm = Mapper.Map<IEnumerable<LandNewsFilterViewModel>, IEnumerable<LandNewsViewModel>>(lstLandNewsHot);


            string filterSaleRent = "lt.TypeExchange = 1" + " and ln.IsDelete = 0 and ln.IsPublished = 1";
            var lstLandNewsSaleRent = _landNewsService.GetAllByFilter(filterSaleRent, "PublishedDate desc", 1, pageSizeSale).ToList();
            var lstLandNewsSaleRentVm = Mapper.Map<IEnumerable<LandNewsFilterViewModel>, IEnumerable<LandNewsViewModel>>(lstLandNewsSaleRent);


            string filterBuyRent = "lt.TypeExchange = 2" + " and ln.IsDelete = 0 and ln.IsPublished = 1";
            var lstLandNewsBuyRent = _landNewsService.GetAllByFilter(filterBuyRent, "PublishedDate desc", 1, pageSizeRent).ToList();
            var lstLandNewsBuyRentVm = Mapper.Map<IEnumerable<LandNewsFilterViewModel>, IEnumerable<LandNewsViewModel>>(lstLandNewsBuyRent);

            homeViewModel.CategoryWard = categoryWard;
            homeViewModel.LandNewsHot = lstLandNewsHotVm;
            homeViewModel.LandNewsSaleAndRent = lstLandNewsSaleRentVm;
            homeViewModel.LandNewsBuyAndRent = lstLandNewsBuyRentVm;
            return View(homeViewModel);
        }


        [ChildActionOnly]
        public ActionResult Header2()
        {
            var lstMenuGroup = _menugroupService.GetMenuGroupActive();
            var lstMenuGroupVm = Mapper.Map<IEnumerable<MenuGroup>, IEnumerable<MenuGroupViewModel>>(lstMenuGroup).OrderBy(x => x.DisplayOrder);
            foreach (var item in lstMenuGroupVm)
            {
                var menu = _menuService.GetMenuActiveByMenuGroup(item.ID);
                item.Menus = Mapper.Map<IEnumerable<Menu>, IEnumerable<MenuViewModel>>(menu);
            }
            ViewBag.UserInfo = UserInfo;
            return PartialView(lstMenuGroupVm);
        }

        [ChildActionOnly]
        public ActionResult Footer2()
        {
            return PartialView();
        }

		[ChildActionOnly]
		[OutputCache(Duration = 3600, Location = System.Web.UI.OutputCacheLocation.Client)]
		public ActionResult CategoryDistrict()
		{
			var categoryWard = _addressCommonService.GetTotalLandNewsOfWards(571).ToList().OrderByDescending(x=>x.TotalLandNews);
			return PartialView(categoryWard);
		}

		public ApplicationUserViewModel UserInfo
        {
            get
            {
                if (Session != null)
                {
                    if (Session[CommonConstants.SessionUser] != null)
                    {
                        return (ApplicationUserViewModel)Session[CommonConstants.SessionUser];
                    }
                }
                return null;
            }
            set
            {
                if (value == null)
                    Session.Remove(CommonConstants.SessionUser);
                else
                    Session[CommonConstants.SessionUser] = value;
            }
        }
    }
}

LandProject.Web/Views/Shared/CategoryDistrict.cshtml
@model IEnumerable<LandProject.Common.CountLandNewsDistrictViewModel>

<a rel="next" target="_blank" href="/nha-dat-ban.html" title="cho thue nha dat">
    <h2 class="mbnd_feature_title_home">
        <span title="Tin mới nhất">DANH MỤC NHÀ ĐẤT</span>
    </h2>
</a>
<ul>
    @if (Model.Count() != 0)
    {
        foreach (var item in Model)
        {
            var url = "/nha-dat/" + HttpUtility.HtmlDecode(item.Name) + ".w-" + item.ID + ".html";
            <li>
                <a rel="next" href="@url">
                    @item.Name (@item.TotalLandNews)
                </a>
                <hr class="mbnd_hr_m_w">
            </li>
        }
    }
</ul>

LandProject.Web/Views/Shared/Footer.cshtml
@{ 
    var categoryWard = (IEnumerable<LandProject.Common.CountLandNewsDistrictViewModel>)ViewBag.CategoryFooter;
}

<section class="footer-content">
    <div class="container">
        <div class="row flow-offset-3">
            <div class="col-xs-12 col-sm-6 col-lg-3">
                <div class="rd-navbar-brand">
                    <a href="index.html" class="brand-name">
                        <img src="https://livedemo00.template-help.com/wt_prod-1143/images/logo-2.png" alt="">
                    </a>
                </div>
                <p>Kênh thông tin rao bán bất động sản</p>
                <address class="address">
                    <dl>
                        <dt>Địa chỉ:</dt>
                        <dd></dd>
                    </dl>
                    <dl class="dl-horizontal-mod-1">
                        <dt>Phone</dt>
                        <dd>
                            <a href="callto:#" class="text-primary">(91) 8547 632521</a>
                        </dd>
                    </dl>
                    <dl class="dl-horizontal-mod-1">
                        <dt>Email</dt>
                        <dd>
                            <a href="/cdn-cgi/l/email-protection#bd9e" class="text-primary"><span class="__cf_email__" data-cfemail="fb92959d94bb989a958d9a88d5989496"></span></a>
                        </dd>
                    </dl>
                </address>
            </div>
            <div class="col-xs-12 col-sm-6 col-lg-3">
                
            </div>
            <div class="col-xs-12 col-sm-6 col-lg-3">
                <h6 class="text-ubold">Tin tức</h6>
                <div class="blog-post text-left">
                    <div class="blog-post-title">
                        <a href="post-page.html" class="text-primary">Điều chỉnh quy hoạch H. Vạn Ninh đến năm 2035
                        </a>
                    </div>
                    <div class="blog-post-time">
                        <time datetime="2016" class="small">2019/05/20</time>
                    </div>
                </div>
                <div class="blog-post text-left">
                    <div class="blog-post-title">
                        <a href="post-page.html" class="text-primary">
                            Điều chỉnh quy hoạch H. Vạn Ninh đến năm 2035
                        </a>
                    </div>
                    <div class="blog-post-time">
                        <time datetime="2016" class="small">2019/05/20</time>
                    </div>
                </div>
                <div class="blog-post text-left">
                    <div class="blog-post-title">
                        <a href="post-page.html" class="text-primary">
                            Điều chỉnh quy hoạch H. Vạn Ninh đến năm 2035
                        </a>
                    </div>
                    <div class="blog-post-time">
                        <time datetime="2016" class="small">2019/05/20</time>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-lg-3">
                <h6 class="text-ubold">Vị trí bất động sản</h6>
                <ul class="list-marked well6 text-left">
                    @if (categoryWard.Count() != 0)
                    {
                        foreach (var item in categoryWard)
                        {
                            var url = "/nha-dat/" + HttpUtility.HtmlDecode(item.Name) + ".w-" + item.ID + ".html";
                            <li>
                                <a href="@url" class="text-sushi">@item.Name (@item.TotalLandNews)</a>
                            </li>
                        }
                    }
                
                </ul>
            </div>
        </div>
    </div>
</section>
<section class="copyright">
    <div class="container">
        <ul class="list-inline pull-sm-right">
            <li>
                <a href="#" class="fa-facebook"></a>
            </li>
            <li>
                <a href="#" class="fa-twitter"></a>
            </li>
            <li>
                <a href="#" class="fa-pinterest-p"></a>
            </li>
            <li>
                <a href="#" class="fa-vimeo"></a>
            </li>
            <li>
                <a href="#" class="fa-google"></a>
            </li>
            <li>
                <a href="#" class="fa-rss"></a>
            </li>
        </ul>
    </div>
</section>
<!-- Rd Mailform result field-->
<div class="rd-mailform-validate"></div>

LandProject.Web/Views/Shared/Header.cshtml
@model IEnumerable<LandProject.Web.Models.MenuGroupViewModel>
@{ 
    var userInfo = (LandProject.Web.Models.ApplicationUserViewModel)ViewBag.UserInfo;
    int index = 0;
}
<nav class="rd-navbar" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fullwidth" data-md-layout="rd-navbar-fullwidth" data-lg-layout="rd-navbar-fullwidth" data-device-layout="rd-navbar-fixed" data-sm-device-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed"
     data-lg-device-layout="rd-navbar-fullwidth" data-stick-up-offset="100px">
    <!--RD Navbar Panel-->
    <div class="rd-navbar-top-panel">
        <div class="rd-navbar-top-panel-wrap">
            <div class="top-panel-inner">
                <dl class="dl-horizontal-mod-1 login">
                    @if (userInfo != null)
                    {                      
                        <dt>
                            <span class="fa-user icon-xxs-mod-2"></span>
                        </dt>
                        <dd>
                            @using (Html.BeginForm("LogOut", "Account", FormMethod.Post, new { @id = "frmLogout" }))
                            {
                                @Html.AntiForgeryToken()
                               <span>@userInfo.UserName</span><a href="#" id="btnLogout"> / đăng xuất</a>
                            }

                            <input name="UserId" id="UserId" value="@userInfo.Id" class="hidden" />
                            <input name="UserId" id="UserName" value="@userInfo.FullName" class="hidden" />
                            <input name="UserId" id="UserMobile" value="@userInfo.PhoneNumber" class="hidden" />
                            <input name="UserId" id="UserAddress" value="@userInfo.Address" class="hidden" />
                            <input name="UserId" id="UserEmail" value="@userInfo.Email" class="hidden" />
                        </dd>

                    }
                    else
                    {
                        <dt>
                            <span class="fa-sign-in icon-xxs-mod-2"></span>
                        </dt>
                        <dd>
                            <input name="UserId" id="UserId" value="" class="hidden" />
                            <input name="UserId" id="UserName" value="" class="hidden" />
                            <input name="UserId" id="UserMobile" value="" class="hidden" />
                            <input name="UserId" id="UserAddress" value="" class="hidden" />
                            <input name="UserId" id="UserEmail" value="" class="hidden" />
                            <a href="/dang-nhap.html" class="text-sushi">Đăng ký/Đăng nhập</a>
                        </dd>
                    }

                </dl>
                @*<dl class="dl-horizontal-mod-1 login">
                    <dt>
                        <span class="fa-user icon-xxs-mod-2"></span>
                    </dt>
                    <dd>
                        <a href="#" class="text-sushi">Đăng nhập</a>
                    </dd>
                </dl>*@
            </div>

            <dl class="dl-horizontal-mod-1">
                <dt>
                    <span class="fa-map-marker icon-xxs-mod-2"></span>
                </dt>
                <dd>
                    <a href="#" class="inset-11">Vạn Ninh, Khánh Hòa</a>
                </dd>
            </dl>
            <dl class="dl-horizontal-mod-1">
                <dt>
                    <span class="fa-phone icon-xxs-mod-2"></span>
                </dt>
                <dd>
                    <a href="callto:#">03-68-68-68-68</a>
                </dd>
            </dl>
            <div class="btn-group">
                <a href="/dang-tin-rao-vat-ban-nha-dat.html" class="btn btn-sm btn-primary fa-plus-circle">  Đăng tin rao</a>
            </div>
        </div>
    </div>
    <div class="rd-navbar-inner inner-wrap">
        <div class="rd-navbar-panel">
            <!-- RD Navbar Toggle-->
            <button data-rd-navbar-toggle=".rd-navbar-nav-wrap" class="rd-navbar-toggle">
                <span></span>
            </button>
            <!-- RD Navbar Brand-->
            <div class="rd-navbar-brand">
                <a href="/" class="brand-name">
                    <img src="https://livedemo00.template-help.com/wt_prod-1143/images/logo-1.png" alt="">
                </a>
            </div>
        </div>
        <div class="btn-group">
            <a href="/dang-tin-rao-vat-ban-nha-dat.html" class="btn btn-sm btn-primary fa-plus-circle">  Đăng tin rao</a>
        </div>
        <div class="rd-navbar-nav-wrap">
            <!-- RD Navbar Nav-->
            <ul class="rd-navbar-nav">
                <li class="active">
                    <a href="/" class="font-seogui">Trang chủ</a>
                </li>
                @if (Model.Count() != 0)
                {
                    foreach (var itemMenuGroup in Model)
                    {
                        <li>
                            <a href="@itemMenuGroup.URL" class="font-seogui" target="@(String.IsNullOrEmpty(itemMenuGroup.Target) == true ? "_self" : itemMenuGroup.Target)">@itemMenuGroup.Name</a>
                            @if (itemMenuGroup.Menus.Count() != 0)
                            {
                                var lstMenu = itemMenuGroup.Menus;
                                <ul class="rd-navbar-dropdown">
                                    @foreach (var itemMenuChild in lstMenu)
                                    {
                                        <li>
                                            <a href="@itemMenuChild.URL" target="@(String.IsNullOrEmpty(itemMenuChild.Target) == true ? "_self" : itemMenuChild.Target)">@itemMenuChild.Name</a>
                                        </li>
                                    }
                                </ul>
                            }
                        </li>
                    }
                }

                <li class="link-group">
                    <a href="/dang-tin-rao-vat-ban-nha-dat.html" target="" class="btn btn-sm btn-primary fa-plus-circle"> Đăng tin rao</a>
                </li>
                <li class="rd-navbar-bottom-panel">
                    <div class="rd-navbar-bottom-panel-wrap">
                        <dl class="dl-horizontal-mod-1 login">
                            <dt>
                                <span class="mdi mdi-login icon-xxs-mod-2"></span>
                            </dt>
                            @if (userInfo != null)
                            {
                                <dd>
                                    <span>@userInfo.UserName</span><a href="#" id="btnLogout"> / đăng xuất</a>
                                </dd>
                            }
                            else
                            {
                                <dd>
                                    <a href="/dang-nhap.html" class="text-sushi">Đăng ký/Đăng nhập</a>
                                </dd>
                            }

                        </dl>
                        <div class="top-panel-inner">
                            <dl class="dl-horizontal-mod-1">
                                <dt>
                                    <span class="icon-xxs-mod-2 fa-phone"></span>
                                </dt>
                                <dd>
                                    <a href="#">03-68-68-68-68</a>
                                </dd>
                            </dl>

                            <address>
                                <dl class="dl-horizontal-mod-1">
                                    <dt>
                                        <span class="icon-xxs-mod-2 mdi fa-map-marker"></span>
                                    </dt>
                                    <dd>
                                        <a href="#" class="inset-11">Vạn ninh, Khánh hòa</a>
                                    </dd>
                                </dl>
                            </address>
                        </div>

                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

LandProject.Web/Views/Shared/Header2.cshtml
@model IEnumerable<LandProject.Web.Models.MenuGroupViewModel>
@{
    var userInfo = (LandProject.Web.Models.ApplicationUserViewModel)ViewBag.UserInfo;
}
<div class="jumbotron head cus_jumbotron_public">
    <div class="container head">
        <div class="row">
            <div class="col-xs-12 col-md-12 <col-lg-12 text-right custext-right_public">
                <img src="http://muabannhadat.vn/img/icons/phone-ic.png" />
                <span class="cus-span-telpublic">Hotline: <b><a href="tel:18001207">0397902222</a></b></span>
            </div>
        </div>
    </div>
</div>
<!--Menu-->
<div class="navbar navbar-default mbnd-navbar">
    <div class="container">
        <div class="row">
            <div class="col-lg-2 visible-lg hidden-xs hidden-sm logo">
                <a href="/">
                    <img src="~/assets/client/img/logo_new.jpg" height="110" width="120" alt="Đất đặc khu" />
                </a>
            </div>
            <div class="col-md-3 visible-md hidden-xs hidden-sm logo">
                <a href="/">
                    <img src="~/assets/client/img/logo_new.jpg" height="110" width="120" alt="Đất đặc khu" />
                </a>
            </div>
            <div class="navbar-header hidden-md hidden-lg">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mainNav"></button>
                <a class="navbar-brand" href="/">
                    <img src="~/assets/client/img/logo_new.jpg" height="90" width="100" alt="Đất đặc khu" />
                </a>
            </div>
            <div class="col-md-10">
                <div class="collapse navbar-collapse big" id="mainNav">
                    <ul class="nav navbar-nav">
                        @if (Model.Count() != 0)
                        {
                            foreach (var itemMenuGroup in Model)
                            {
                                var itemMenuChild = itemMenuGroup.Menus;
                                int countItemMenuChild = itemMenuGroup.Menus.Count();
                                <li class="dropdown has-hover">
                                    <a href="@itemMenuGroup.URL" class="dropdown-toggle" target="@(String.IsNullOrEmpty(itemMenuGroup.Target) == true ? "_self" : itemMenuGroup.Target)">
                                        @itemMenuGroup.Name
                                        @if (countItemMenuChild != 0)
                                        {
                                            <img class="img-arrow" height="8" src="http://muabannhadat.vn/Content/img/Ico-arrow-down.svg" alt="">
                                        }
                                    </a>
                                    @if (countItemMenuChild != 0)
                                    {
                                        <a class="button-dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                            <img height="10" src="http://muabannhadat.vn/Content/img/Ico-arrow-down.svg" alt="">
                                        </a>
                                        <ul class="dropdown-menu">
                                            @foreach (var itemChild in itemMenuChild)
                                            {
                                                <li><a href="@itemChild.URL">@itemChild.Name</a></li>
                                            }
                                        </ul>
                                    }
                                </li>
                            }
                        }
                    </ul>
                    @if (userInfo != null)
                    {
                        <ul id="loginStatus" class="nav navbar-right navbar-nav">
                            <li>
                                <a href="/thanh-vien/tin-dang.html"> @userInfo.UserName </a>
                            </li>
                            <li class="nav-register">
                                <a href="#" id="btnLogout"> Thoát</a>
                                <input name="UserId" id="UserId" value="@userInfo.Id" class="hidden" />
                                <input name="UserId" id="UserName" value="@userInfo.FullName" class="hidden" />
                                <input name="UserId" id="UserMobile" value="@userInfo.PhoneNumber" class="hidden" />
                                <input name="UserId" id="UserAddress" value="@userInfo.Address" class="hidden" />
                                <input name="UserId" id="UserEmail" value="@userInfo.Email" class="hidden" />
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul id="loginStatus" class="nav navbar-right navbar-nav">
                            <li>
                                <a href="/dang-nhap.html">Đăng nhập</a>
                            </li>
                            <li class="nav-register">
                                <a href="/dang-ky.html">Đăng ký</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

LandProject.Web/Views/Shared/_LayoutLand_v2.cshtml
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8" />
    <link rel="publisher" href="https://plus.google.com/+datdackhu" />
    <!-- Site Title-->
    <title>@ViewBag.Title</title>

    <meta property="og:locale" content="vi_VN" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta content="~/assets/client/img/logo_new.jpg" property="og:image" />
    <meta property="og:image:width" content="200" />
    <meta property="og:image:height" content="200" />
    <meta name="msvalidate.01" content="A308E85101FF5B11536223A09983A432" />
    <meta name="alexaVerifyID" content="S2-myIVTmc9TJ0ILBN9tFPVgv-4" />
    <meta name="google-site-verification" content="Rt_gkL-fAy8toQ5xDNpw-9svn_7s1u6iXxM8D_8Xpdw" />
    <meta name="robots" content="index,follow" />
    <meta name="description" content="Mua bán nhà đất (bất động sản VN) » 100 ngàn tin mới nhất: Bán nhà, thuê nhà, căn hộ chung cư, sang nhượng nhà, đất nền » Datdackhu.vn ✓ Giá từ 20tr/m2." />
    <meta content="trang thông tin mua bán bất động sản | muabannhadat datdackhu" property="og:title" />
    <meta content="Mua bán nhà đất (bất động sản VN) » 100 ngàn tin mới nhất: Bán nhà, thuê nhà, căn hộ chung cư, sang nhượng nhà, đất nền » Datdackhu.vn ✓ Giá từ 20tr/m2." property="og:description" />
    <meta content="1576235492626228" property="fb:app_id" />
    <meta content="website" property="og:type" />
    <meta content="http://www.datdackhu.vn/" property="og:url" />
    <meta content="2019-06-04T11:17:58+07:00" property="og:updated_time" />
    <meta name="msapplication-square70x70logo" content="~/assets/client/img/logo_new.jpg" />
    <meta name="msapplication-square150x150logo" content="~/assets/client/img/logo_new.jpg" />
    <meta name="msapplication-wide310x150logo" content="~/assets/client/img/logo_new.jpg" />
    <meta name="msapplication-square310x310logo" content="~/assets/client/img/logo_new.jpg" />
    <link rel="apple-touch-icon" href="~/assets/client/img/logo_new.jpg" />
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/client/img/logo_new.jpg" />
    <link rel="apple-touch-icon" sizes="120x120" href="~/assets/client/img/logo_new.jpg" />
    <link rel="apple-touch-icon" sizes="152x152" href="~/assets/client/img/logo_new.jpg" />
    <link rel="dns-prefetch" href="https://www.google-analytics.com/" />
    <link rel="dns-prefetch" href="https://www.googletagmanager.com/" />
    <link rel="dns-prefetch" href="https://www.facebook.com" />
    <link rel="dns-prefetch" href="https://www.doubleclickbygoogle.com/" />
    <link rel="shortcut icon" type="image/jpg" href="https://datdackhu.vn/assets/client/img/favicon.ico" sizes="120x120">
    <link rel="shortcut icon" type="image/x-icon" href="https://datdackhu.vn/assets/client/img/logo_new.jpg" />

    <link href="~/assets/vendors/font-awesome/css/font-awesome.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">*@
    <link href="~/assets/client_v2/css/style.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
</head>
<body>
    <!--Header-->
    @{Html.RenderAction("Header2", "Home2"); }
    <!--Body-->
    <div class="body-content">
        @RenderBody()
    </div>
    <!--Footer-->
    <footer id="footer">
        @{Html.RenderAction("Footer2", "Home2"); }
    </footer>

    <!--init-->
    <script src="~/assets/client_v2/js/common_ddk.min.js"></script>
    <script src="~/assets/vendors/toastr/toastr.min.js"></script>
    <!-- blockUI -->
    <script src="~/assets/vendors/blockUI/jquery.blockUI.min.js"></script>
    <script> var _Host = "@Url.Content("~")";</script>
    <!-- ajax helper -->
    <script src="~/assets/library/helper/CallServiceHelper.js"></script>
    <script src="~/assets/client_v2/js/ddkapi.js"></script>
    <!-- count ipv4 -->
    <script src="~/assets/client/js/countIPv4AccessPage.js"></script>
    <script type="text/javascript">
        window.onload = function () {
            mbndApi.initMbndApi();
        }
    </script>
    <script>
        $(window).scroll(function () {
            var scroll = $(window).scrollTop();

            if (scroll >= 200) {
                $(".mbnd-navbar").addClass("navbar-fixed-top");
            } else {
                $(".mbnd-navbar").removeClass("navbar-fixed-top");
            }
        });
    </script>
    <script>
         function gettoken() {
            var token = '@Html.AntiForgeryToken()';
            token = $(token).val();
            return token;
          }
        $('body').on('click', '#btnLogout', function (e) {
            $.ajax({
                type: "POST",
                url: _Host + "Account/LogOut",
                data: {
                    __RequestVerificationToken: gettoken(),
                },
                dataType: 'json',
                contentType: 'application/x-www-form-urlencoded; charset=utf-8',
                success: function (response) {
                    console.log(response)
                    if (response.status) {
                        window.location.href = _Host;
                    }
                },
            });
        });
    </script>
    @RenderSection("footerJS", required: false)
</body>
</html>